### ISSUE TITLE
was looking for fireship.io discord server...

### ISSUE THREAD

**Issue by fire17** [fireship-io/tailwind-dashboard#7]
hey yo ! hope you are well
was looking for a fireship.io server on discord, instead found jeff made his own discord :P
well i wish it was more than a visual demo
anyhow do you guys have a community on discord or somewhere else?

looking for like-minded people to work on some foss projects
people with a wide stack of abilities needed for real world solutions
seems that fireship.io is the perfect host for people like that :)

would love any advice you got on the matter
thanks a lot and have a good one !

**Comment by klutchdev** [comment]
@fire17 Hey, we have a Slack channel - nothing as far as discord goes though. 
Here's the link, you should come check it out!
[Fireship Slack](angularfirebase.slack.com)
